### ISSUE TITLE
handle case where oldstta is None

### ISSUE THREAD

**Issue by rcmiller** [mit-eecs/issue-tracker#102]
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)

  File "/mit/eecs/Scripts/django/coursemgmt/views.py", line 3343, in staff_basic_information
    if oldstta.status == 'AOK':

AttributeError: 'NoneType' object has no attribute 'status'

**Comment by rcmiller** [comment]
fixed
